### ISSUE TITLE
problem with Template and the new CI 3.0-dev

### ISSUE THREAD

**Issue by zaherg** [philsturgeon/codeigniter-template#35]
hi, 
i have just downloaded the new CI-3.0-dev ( 24/05/2012 )
and when i run my application i got this error :

``` php
A PHP Error was encountered
Severity: Runtime Notice

Message: Only variables should be assigned by reference

Filename: libraries/Template.php

Line Number: 281
```

which is 

``` php
$title_segments =& func_get_args();
```

and remove it will cause the title to show the only title which we have passed inside the function controller, not even the one inside the constructor  ..

**Comment by secrethash** [comment]
Hey @linuxjuggler , did you find the solution for the problem?

**Comment by korneliuskristianr** [comment]
Thanks mr @jonsuh it work for me
